name: fooddeliveryapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  splash: ^1.1.0


  
  cupertino_icons: ^1.0.2

  #STATE_MANAGEMENT
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  


dev_dependencies:
  
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  stacked_generator: ^1.5.1
  flutter_test:
    sdk: flutter  


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  - assets/
  #   - images/a_dot_ham.jpeg

